// <auto-generated />
using System;
using InventoryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728105928_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5319fb65-b5d2-4433-9541-d8d153596aa1"),
                            Category = "Electronics",
                            Description = "15-inch laptop",
                            Name = "Laptop",
                            Price = 1200.00m,
                            Quantity = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("79c32404-d256-4433-ac5a-e6f146647782"),
                            Category = "Electronics",
                            Description = "Wireless mouse",
                            Name = "Mouse",
                            Price = 25.99m,
                            Quantity = 25,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f7515dc8-23b0-4d69-afed-b61427cff1fc"),
                            Category = "Electronics",
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 75.50m,
                            Quantity = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fda23346-bf1d-4570-b50f-4eb320270aa0"),
                            Category = "Electronics",
                            Description = "24-inch monitor",
                            Name = "Monitor",
                            Price = 150.00m,
                            Quantity = 8,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("883d01d6-5607-4ec1-92bd-78746889bef8"),
                            Category = "Furniture",
                            Description = "Ergonomic chair",
                            Name = "Desk Chair",
                            Price = 200.00m,
                            Quantity = 5,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("b5d3496c-eff3-4fbe-b493-7295981e7bf9"),
                            Category = "Accessories",
                            Description = "Type-C USB cable",
                            Name = "USB Cable",
                            Price = 9.99m,
                            Quantity = 50,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4ee2c2a9-13f5-4dac-8c37-5f353268e585"),
                            Category = "Stationery",
                            Description = "A5 ruled notebook",
                            Name = "Notebook",
                            Price = 3.50m,
                            Quantity = 100,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5d234ee2-3f43-44ba-8ab4-28abf3bb06a2"),
                            Category = "Stationery",
                            Description = "Blue ink pen",
                            Name = "Pen",
                            Price = 1.00m,
                            Quantity = 200,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f2991aa2-bbef-4297-9bd9-a89904bec274"),
                            Category = "Furniture",
                            Description = "LED desk lamp",
                            Name = "Desk Lamp",
                            Price = 45.00m,
                            Quantity = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d97e2ba9-bcfa-4533-9251-5163b261036e"),
                            Category = "Electronics",
                            Description = "1TB external hard drive",
                            Name = "External HDD",
                            Price = 80.00m,
                            Quantity = 12,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
