// <auto-generated />
using System;
using InventoryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Electronics",
                            Description = "15-inch laptop",
                            Name = "Laptop",
                            Price = 1200.00m,
                            Quantity = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Electronics",
                            Description = "Wireless mouse",
                            Name = "Mouse",
                            Price = 25.99m,
                            Quantity = 25,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Electronics",
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 75.50m,
                            Quantity = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Electronics",
                            Description = "24-inch monitor",
                            Name = "Monitor",
                            Price = 150.00m,
                            Quantity = 8,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Furniture",
                            Description = "Ergonomic chair",
                            Name = "Desk Chair",
                            Price = 200.00m,
                            Quantity = 5,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Accessories",
                            Description = "Type-C USB cable",
                            Name = "USB Cable",
                            Price = 9.99m,
                            Quantity = 50,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Stationery",
                            Description = "A5 ruled notebook",
                            Name = "Notebook",
                            Price = 3.50m,
                            Quantity = 100,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Stationery",
                            Description = "Blue ink pen",
                            Name = "Pen",
                            Price = 1.00m,
                            Quantity = 200,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = "Furniture",
                            Description = "LED desk lamp",
                            Name = "Desk Lamp",
                            Price = 45.00m,
                            Quantity = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "Electronics",
                            Description = "1TB external hard drive",
                            Name = "External HDD",
                            Price = 80.00m,
                            Quantity = 12,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
